### ISSUE TITLE
panic: send on closed channel in TestConnectivityVNet/Symmetric_NATs_on_both_ends

### ISSUE THREAD

**Issue by at-wat** [pion/ice#150]
environment: CI: Test i386 1.13

It randomly fails on CI environment.
```
=== RUN   TestConnectivityVNet/Symmetric_NATs_on_both_ends
turn ERROR: 2020/01/25 01:14:13 Packet unhandled in relay src 28.1.1.1:49157
panic: send on closed channel

goroutine 249 [running]:
github.com/pion/turn/v2/internal/client.(*Transaction).WriteResult(0x923d5e0, 0x9223290, 0x841e5a0, 0x92c5ac0, 0x0, 0x0, 0x0, 0x34)
	/go/pkg/mod/github.com/pion/turn/v2@v2.0.0/internal/client/transaction.go:83 +0x39
github.com/pion/turn/v2.(*Client).handleSTUNMessage(0x908e320, 0x927a000, 0x34, 0xffff, 0x841e5a0, 0x92c5ac0, 0x0, 0x0)
	/go/pkg/mod/github.com/pion/turn/v2@v2.0.0/client.go:471 +0x461
github.com/pion/turn/v2.(*Client).HandleInbound(0x908e320, 0x927a000, 0x34, 0xffff, 0x841e5a0, 0x92c5ac0, 0x92c5ac0, 0x0, 0x0)
	/go/pkg/mod/github.com/pion/turn/v2@v2.0.0/client.go:398 +0x202
github.com/pion/turn/v2.(*Client).Listen.func1(0x908e320)
	/go/pkg/mod/github.com/pion/turn/v2@v2.0.0/client.go:172 +0xba
created by github.com/pion/turn/v2.(*Client).Listen
	/go/pkg/mod/github.com/pion/turn/v2@v2.0.0/client.go:163 +0xd8
FAIL	github.com/pion/ice	36.062s
FAIL
```

**Comment by at-wat** [comment]
Reproduced also on local environment in rare case. (`-count=100`)

https://github.com/pion/ice/pull/151 seems suppressing it? (no idea why, but no error with `-count=100`)
