### ISSUE TITLE
nil pointer dereference on error handling

### ISSUE THREAD

**Issue by lueurxax** [pion/ice#177]
### Your environment.
  - Version: v0.7.12
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x88be1f]

goroutine 6116 [running]:
github.com/pion/ice.closeConnAndLog(0x0, 0x0, 0xb3b160, 0xc006a56940, 0xc00229fe80, 0x39)
	/go/pkg/mod/github.com/pion/ice@v0.7.12/gather.go:26 +0x5f
github.com/pion/ice.(*Agent).gatherCandidatesSrflx.func1(0xc006943550, 0xc005be9400, 0x1, 0xa48beb, 0x12, 0x4b66, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/pion/ice@v0.7.12/gather.go:260 +0x4fd
created by github.com/pion/ice.(*Agent).gatherCandidatesSrflx
	/go/pkg/mod/github.com/pion/ice@v0.7.12/gather.go:249 +0x189
```
### What did you do?
I think this is due to a listenUDPInPortRange return error, and conn is nil.

**Comment by lueurxax** [comment]
I think it's right version of closeConnAndLog
