### ISSUE TITLE
go test failure on master (segmentation violation)

### ISSUE THREAD

**Issue by nerd2** [pion/ice#202]
### Your environment.
  - Version: 3b470331467299f1cb7d3b0b9a3955e396231521

### What did you do?

Ran `go test`

### What did you expect?

Test to pass

### What happened?

sam@samubuntu:~/Dev/pion/ice$ go test
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x752230]

goroutine 91 [running]:
github.com/pion/ice/v2.(*Agent).handleInbound(0xc0000aea00, 0xc000088460, 0x904580, 0xc0000b0500, 0x8fa660, 0xc00028a030)
	/home/sam/Dev/pion/ice/agent.go:922 +0x800
github.com/pion/ice/v2.handleInboundCandidateMsg.func1(0xc0000aea00)
	/home/sam/Dev/pion/ice/candidate_base.go:113 +0x58
github.com/pion/ice/v2.(*Agent).run(0xc0000aea00, 0xc00044ef10, 0xc000112000, 0xc00028c000, 0x0)
	/home/sam/Dev/pion/ice/agent.go:168 +0x262
github.com/pion/ice/v2.handleInboundCandidateMsg(0x904580, 0xc0000b0500, 0xc00017c000, 0x70, 0x2000, 0x8fa660, 0xc00028a030, 0x902a40, 0xc00007c000)
	/home/sam/Dev/pion/ice/candidate_base.go:112 +0x538
github.com/pion/ice/v2.(*candidateBase).recvLoop(0xc0000b0500)
	/home/sam/Dev/pion/ice/candidate_base.go:97 +0xe1
created by github.com/pion/ice/v2.(*candidateBase).start
	/home/sam/Dev/pion/ice/candidate_base.go:81 +0xe0
exit status 2
FAIL	github.com/pion/ice/v2	4.349s

**Comment by nerd2** [comment]
I had a quick look into this but unfortunately dont have enough context to understand how it should work.

One example failure path (may be the only one) is transport_test.go::connect - where "gatherAndExchangeCandidates" runs before "Accept"/"Dial"

**Comment by at-wat** [comment]
What version of Go and arch do you use? (`go version`)
The error log doesn't have information that which test failed. Could you try `go test -v`?

**Comment by nerd2** [comment]
It occurs with different tests, racily randomly

```
sam@samubuntu:~/Dev/pion/ice$ go version
go version go1.14.2 linux/amd64
sam@samubuntu:~/Dev/pion/ice$ go test -v
=== RUN   TestPairSearch
--- PASS: TestPairSearch (0.00s)
=== RUN   TestPairPriority
--- PASS: TestPairPriority (0.00s)
=== RUN   TestOnSelectedCandidatePairChange
--- PASS: TestOnSelectedCandidatePairChange (0.00s)
=== RUN   TestHandlePeerReflexive
=== RUN   TestHandlePeerReflexive/UDP_pflx_candidate_from_handleInbound()
=== RUN   TestHandlePeerReflexive/Bad_network_type_with_handleInbound()
=== RUN   TestHandlePeerReflexive/Success_from_unknown_remote,_prflx_candidate_MUST_only_be_created_via_Binding_Request
--- PASS: TestHandlePeerReflexive (0.42s)
    --- PASS: TestHandlePeerReflexive/UDP_pflx_candidate_from_handleInbound() (0.00s)
    --- PASS: TestHandlePeerReflexive/Bad_network_type_with_handleInbound() (0.01s)
    --- PASS: TestHandlePeerReflexive/Success_from_unknown_remote,_prflx_candidate_MUST_only_be_created_via_Binding_Request (0.00s)
=== RUN   TestConnectivityOnStartup
--- PASS: TestConnectivityOnStartup (0.40s)
=== RUN   TestConnectivityLite
--- PASS: TestConnectivityLite (2.40s)
=== RUN   TestInboundValidity
=== RUN   TestInboundValidity/Invalid_Binding_requests_should_be_discarded
=== RUN   TestInboundValidity/Invalid_Binding_success_responses_should_be_discarded
=== RUN   TestInboundValidity/Discard_non-binding_messages
=== RUN   TestInboundValidity/Valid_bind_request
=== RUN   TestInboundValidity/Valid_bind_without_fingerprint
=== RUN   TestInboundValidity/Success_with_invalid_TransactionID
--- PASS: TestInboundValidity (0.41s)
    --- PASS: TestInboundValidity/Invalid_Binding_requests_should_be_discarded (0.00s)
    --- PASS: TestInboundValidity/Invalid_Binding_success_responses_should_be_discarded (0.00s)
    --- PASS: TestInboundValidity/Discard_non-binding_messages (0.00s)
    --- PASS: TestInboundValidity/Valid_bind_request (0.00s)
    --- PASS: TestInboundValidity/Valid_bind_without_fingerprint (0.00s)
    --- PASS: TestInboundValidity/Success_with_invalid_TransactionID (0.00s)
=== RUN   TestInvalidAgentStarts
--- PASS: TestInvalidAgentStarts (0.50s)
=== RUN   TestConnectionStateCallback
--- PASS: TestConnectionStateCallback (2.90s)
=== RUN   TestInvalidGather
=== RUN   TestInvalidGather/Gather_with_no_OnCandidate_should_error
--- PASS: TestInvalidGather (0.00s)
    --- PASS: TestInvalidGather/Gather_with_no_OnCandidate_should_error (0.00s)
=== RUN   TestCandidatePairStats
--- PASS: TestCandidatePairStats (0.40s)
=== RUN   TestLocalCandidateStats
--- PASS: TestLocalCandidateStats (0.40s)
=== RUN   TestRemoteCandidateStats
--- PASS: TestRemoteCandidateStats (0.40s)
=== RUN   TestInitExtIPMapping
--- PASS: TestInitExtIPMapping (0.40s)
=== RUN   TestBindingRequestTimeout
--- PASS: TestBindingRequestTimeout (0.40s)
=== RUN   TestAgentCredentials
--- PASS: TestAgentCredentials (0.00s)
=== RUN   TestConnectionStateFailedDeleteAllCandidates
--- PASS: TestConnectionStateFailedDeleteAllCandidates (2.65s)
=== RUN   TestConnectionStateConnectingToFailed
--- PASS: TestConnectionStateConnectingToFailed (2.40s)
=== RUN   TestAgentRestart
=== RUN   TestAgentRestart/Restart_During_Gather
=== RUN   TestAgentRestart/Restart_When_Closed
=== RUN   TestAgentRestart/Restart_One_Side
=== RUN   TestAgentRestart/Restart_Both_Sides
--- PASS: TestAgentRestart (2.45s)
    --- PASS: TestAgentRestart/Restart_During_Gather (0.00s)
    --- PASS: TestAgentRestart/Restart_When_Closed (0.00s)
    --- PASS: TestAgentRestart/Restart_One_Side (2.00s)
    --- PASS: TestAgentRestart/Restart_Both_Sides (0.05s)
=== RUN   TestRelayOnlyConnection
--- PASS: TestRelayOnlyConnection (2.40s)
=== RUN   TestServerReflexiveOnlyConnection
--- PASS: TestServerReflexiveOnlyConnection (2.40s)
=== RUN   TestCandidatePriority
--- PASS: TestCandidatePriority (0.00s)
=== RUN   TestCandidateLastSent
--- PASS: TestCandidateLastSent (0.00s)
=== RUN   TestCandidateLastReceived
--- PASS: TestCandidateLastReceived (0.00s)
=== RUN   TestCandidatePairPriority
--- PASS: TestCandidatePairPriority (0.00s)
=== RUN   TestCandidatePairEquality
--- PASS: TestCandidatePairEquality (0.00s)
=== RUN   TestConnectivityVNet
=== RUN   TestConnectivityVNet/Full-cone_NATs_on_both_ends
=== RUN   TestConnectivityVNet/Symmetric_NATs_on_both_ends
=== RUN   TestConnectivityVNet/1:1_NAT_with_host_candidate_vs_Symmetric_NATs
=== RUN   TestConnectivityVNet/1:1_NAT_with_srflx_candidate_vs_Symmetric_NATs
--- PASS: TestConnectivityVNet (9.40s)
    --- PASS: TestConnectivityVNet/Full-cone_NATs_on_both_ends (3.00s)
    --- PASS: TestConnectivityVNet/Symmetric_NATs_on_both_ends (4.00s)
    --- PASS: TestConnectivityVNet/1:1_NAT_with_host_candidate_vs_Symmetric_NATs (0.00s)
    --- PASS: TestConnectivityVNet/1:1_NAT_with_srflx_candidate_vs_Symmetric_NATs (2.00s)
=== RUN   TestDisconnectedToConnected
--- PASS: TestDisconnectedToConnected (1.44s)
=== RUN   TestWriteUseValidPair
--- PASS: TestWriteUseValidPair (0.42s)
=== RUN   TestExternalIPMapper
=== RUN   TestExternalIPMapper/validateIPString
=== RUN   TestExternalIPMapper/newExternalIPMapper
=== RUN   TestExternalIPMapper/newExternalIPMapper_with_explicit_local_IP
=== RUN   TestExternalIPMapper/newExternalIPMapper_with_inplicit_and_explicit_local_IP
=== RUN   TestExternalIPMapper/findExternalIP_without_explicit_local_IP
=== RUN   TestExternalIPMapper/findExternalIP_with_explicit_local_IP
=== RUN   TestExternalIPMapper/findExternalIP_with_empty_map
--- PASS: TestExternalIPMapper (0.00s)
    --- PASS: TestExternalIPMapper/validateIPString (0.00s)
    --- PASS: TestExternalIPMapper/newExternalIPMapper (0.00s)
    --- PASS: TestExternalIPMapper/newExternalIPMapper_with_explicit_local_IP (0.00s)
    --- PASS: TestExternalIPMapper/newExternalIPMapper_with_inplicit_and_explicit_local_IP (0.00s)
    --- PASS: TestExternalIPMapper/findExternalIP_without_explicit_local_IP (0.00s)
    --- PASS: TestExternalIPMapper/findExternalIP_with_explicit_local_IP (0.00s)
    --- PASS: TestExternalIPMapper/findExternalIP_with_empty_map (0.00s)
=== RUN   TestListenUDP
--- PASS: TestListenUDP (0.00s)
=== RUN   TestSTUNConcurrency
--- PASS: TestSTUNConcurrency (5.20s)
=== RUN   TestTURNConcurrency
=== RUN   TestTURNConcurrency/UDP_Relay
=== RUN   TestTURNConcurrency/TCP_Relay
=== RUN   TestTURNConcurrency/TLS_Relay
=== RUN   TestTURNConcurrency/DTLS_Relay
--- PASS: TestTURNConcurrency (8.02s)
    --- PASS: TestTURNConcurrency/UDP_Relay (0.00s)
    --- PASS: TestTURNConcurrency/TCP_Relay (0.00s)
    --- PASS: TestTURNConcurrency/TLS_Relay (0.01s)
    --- PASS: TestTURNConcurrency/DTLS_Relay (0.00s)
=== RUN   TestCloseConnLog
--- PASS: TestCloseConnLog (0.00s)
=== RUN   TestVNetGather
=== RUN   TestVNetGather/No_local_IP_address
=== RUN   TestVNetGather/Gather_a_dynamic_IP_address
=== RUN   TestVNetGather/listenUDP
--- PASS: TestVNetGather (0.40s)
    --- PASS: TestVNetGather/No_local_IP_address (0.00s)
    --- PASS: TestVNetGather/Gather_a_dynamic_IP_address (0.00s)
    --- PASS: TestVNetGather/listenUDP (0.00s)
=== RUN   TestVNetGatherWithNAT1To1
=== RUN   TestVNetGatherWithNAT1To1/gather_1:1_NAT_external_IPs_as_host_candidates
=== RUN   TestVNetGatherWithNAT1To1/gather_1:1_NAT_external_IPs_as_srflx_candidates
--- PASS: TestVNetGatherWithNAT1To1 (0.40s)
    --- PASS: TestVNetGatherWithNAT1To1/gather_1:1_NAT_external_IPs_as_host_candidates (0.00s)
    --- PASS: TestVNetGatherWithNAT1To1/gather_1:1_NAT_external_IPs_as_srflx_candidates (0.00s)
=== RUN   TestVNetGatherWithInterfaceFilter
=== RUN   TestVNetGatherWithInterfaceFilter/InterfaceFilter_should_exclude_the_interface
=== RUN   TestVNetGatherWithInterfaceFilter/InterfaceFilter_should_not_exclude_the_interface
--- PASS: TestVNetGatherWithInterfaceFilter (0.40s)
    --- PASS: TestVNetGatherWithInterfaceFilter/InterfaceFilter_should_exclude_the_interface (0.00s)
    --- PASS: TestVNetGatherWithInterfaceFilter/InterfaceFilter_should_not_exclude_the_interface (0.00s)
=== RUN   TestConnectedState_String
--- PASS: TestConnectedState_String (0.00s)
=== RUN   TestGatheringState_String
--- PASS: TestGatheringState_String (0.00s)
=== RUN   TestControlled_GetFrom
=== RUN   TestControlled_GetFrom/IncorrectSize
--- PASS: TestControlled_GetFrom (0.00s)
    --- PASS: TestControlled_GetFrom/IncorrectSize (0.00s)
=== RUN   TestControlling_GetFrom
=== RUN   TestControlling_GetFrom/IncorrectSize
--- PASS: TestControlling_GetFrom (0.00s)
    --- PASS: TestControlling_GetFrom/IncorrectSize (0.00s)
=== RUN   TestControl_GetFrom
=== RUN   TestControl_GetFrom/Blank
=== RUN   TestControl_GetFrom/Controlling
=== RUN   TestControl_GetFrom/Controlling/IncorrectSize
=== RUN   TestControl_GetFrom/Controlled
=== RUN   TestControl_GetFrom/Controlled/IncorrectSize
--- PASS: TestControl_GetFrom (0.00s)
    --- PASS: TestControl_GetFrom/Blank (0.00s)
    --- PASS: TestControl_GetFrom/Controlling (0.00s)
        --- PASS: TestControl_GetFrom/Controlling/IncorrectSize (0.00s)
    --- PASS: TestControl_GetFrom/Controlled (0.00s)
        --- PASS: TestControl_GetFrom/Controlled/IncorrectSize (0.00s)
=== RUN   TestMulticastDNSOnlyConnection
--- PASS: TestMulticastDNSOnlyConnection (2.40s)
=== RUN   TestMulticastDNSMixedConnection
--- PASS: TestMulticastDNSMixedConnection (2.40s)
=== RUN   TestMulticastDNSStaticHostName
--- PASS: TestMulticastDNSStaticHostName (0.40s)
=== RUN   TestNetworkTypeParsing_Success
--- PASS: TestNetworkTypeParsing_Success (0.00s)
=== RUN   TestNetworkTypeParsing_Failure
--- PASS: TestNetworkTypeParsing_Failure (0.00s)
=== RUN   TestPriority_GetFrom
=== RUN   TestPriority_GetFrom/IncorrectSize
--- PASS: TestPriority_GetFrom (0.00s)
    --- PASS: TestPriority_GetFrom/IncorrectSize (0.00s)
=== RUN   TestStressDuplex
--- PASS: TestStressDuplex (0.45s)
=== RUN   TestTimeout
    TestTimeout: transport_test.go:54: Connection timed out in 6000.138167 msec
    TestTimeout: transport_test.go:54: Connection timed out in 6000.124216 msec
--- PASS: TestTimeout (12.06s)
=== RUN   TestReadClosed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x752230]

goroutine 1087 [running]:
github.com/pion/ice/v2.(*Agent).handleInbound(0xc0000aef00, 0xc000453810, 0x904580, 0xc0003a80a0, 0x8fa660, 0xc00016b5c0)
	/home/sam/Dev/pion/ice/agent.go:922 +0x800
github.com/pion/ice/v2.handleInboundCandidateMsg.func1(0xc0000aef00)
	/home/sam/Dev/pion/ice/candidate_base.go:113 +0x58
github.com/pion/ice/v2.(*Agent).run(0xc0000aef00, 0xc000687f10, 0xc000038de0, 0xc00056a150, 0x0)
	/home/sam/Dev/pion/ice/agent.go:168 +0x262
github.com/pion/ice/v2.handleInboundCandidateMsg(0x904580, 0xc0003a80a0, 0xc000412000, 0x70, 0x2000, 0x8fa660, 0xc00016b5c0, 0x902a40, 0xc00033ed00)
	/home/sam/Dev/pion/ice/candidate_base.go:112 +0x538
github.com/pion/ice/v2.(*candidateBase).recvLoop(0xc0003a80a0)
	/home/sam/Dev/pion/ice/candidate_base.go:97 +0xe1
created by github.com/pion/ice/v2.(*candidateBase).start
	/home/sam/Dev/pion/ice/candidate_base.go:81 +0xe0
exit status 2
FAIL	github.com/pion/ice/v2	64.809s
```

**Comment by Sean-Der** [comment]
Oof maybe I introduced this. Are you able to pin this down to one commit @nerd2 ? I will work on reproducing.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x752230]

goroutine 1087 [running]:
github.com/pion/ice/v2.(*Agent).handleInbound(0xc0000aef00, 0xc000453810, 0x904580, 0xc0003a80a0, 0x8fa660, 0xc00016b5c0)
```

I don't know any easy way to debug this from the log. Not a nil pointer, so I guess `a.selector` is invalid? But we set `a.selector` in a `a.run` so doesn't seem possible to have a racey read/write. @at-wat you are a better debugger then me :)

**Comment by at-wat** [comment]
Hmm, i couldn't reproduce segmentation fault, but I got many timeout failures https://github.com/pion/ice/issues/204.

**Comment by at-wat** [comment]
I could reproduce it, but the timeout errors are quite frequent on my environment...

**Comment by at-wat** [comment]
With trace
```
=== RUN   TestConnectivityOnStartup
ice WARNING: 2020/06/26 10:21:42 vnet is enabled
ice TRACE: 10:21:42.584755 agent.go:433: Set selected candidate pair: <nil>
ice WARNING: 2020/06/26 10:21:42 vnet is enabled
ice TRACE: 10:21:42.585149 agent.go:433: Set selected candidate pair: <nil>
ice DEBUG: 10:21:42.585494 agent.go:339: Started agent: isControlling? true, remoteUfrag: "yzbIoSKFYlBFgfpl", remotePwd: "PlfMeALFcUIrKhjjLfRMvTqoljVsRrbT"
ice INFO: 2020/06/26 10:21:42 Setting new connection state: Checking
ice TRACE: 10:21:42.585669 agent.go:453: pinging all candidates
ice TRACE: 10:21:42.585805 agent.go:779: ping STUN from host 192.168.0.2:5425 to host 192.168.0.1:5540
ice DEBUG: 10:21:42.585994 agent.go:339: Started agent: isControlling? false, remoteUfrag: "dHlcnbHVTULkkjEK", remotePwd: "meZBdkdJLcwNeBImwltSFUGUBhIHZNHN"
ice TRACE: 10:21:42.586140 agent.go:923: inbound STUN (Request) from 192.168.0.2:5425 to host 192.168.0.1:5540
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x751d50]

goroutine 83 [running]:
github.com/pion/ice/v2.(*Agent).handleInbound(0xc0000c8780, 0xc0000cc1e0, 0x9048a0, 0xc0000ea000, 0x8fa980, 0xc00009cf30)
	/home/at-wat/go/src/github.com/pion/ice/agent.go:925 +0x800
github.com/pion/ice/v2.handleInboundCandidateMsg.func1(0xc0000c8780)
	/home/at-wat/go/src/github.com/pion/ice/candidate_base.go:113 +0x58
github.com/pion/ice/v2.(*Agent).run(0xc0000c8780, 0xc00005df10, 0xc00008e0c0, 0xc000314150, 0x1000000000001)
	/home/at-wat/go/src/github.com/pion/ice/agent.go:168 +0x262
github.com/pion/ice/v2.handleInboundCandidateMsg(0x9048a0, 0xc0000ea000, 0xc000214000, 0x70, 0x2000, 0x8fa980, 0xc00009cf30, 0x902d60, 0xc0000df680)
	/home/at-wat/go/src/github.com/pion/ice/candidate_base.go:112 +0x538
github.com/pion/ice/v2.(*candidateBase).recvLoop(0xc0000ea000)
	/home/at-wat/go/src/github.com/pion/ice/candidate_base.go:97 +0xe1
created by github.com/pion/ice/v2.(*candidateBase).start
	/home/at-wat/go/src/github.com/pion/ice/candidate_base.go:81 +0xe0
FAIL	github.com/pion/ice/v2	1.453s
FAIL
```

**Comment by at-wat** [comment]
`a.selector` is initialized on calling `Dial()/Accept()`, but `candidateBase.recvLoop()` starts on `AddRemoteCandidate()` which is called before `Dial()/Accept()`.
