### ISSUE TITLE
Routine leak in TestSTUNTURNConcurrency

### ISSUE THREAD

**Issue by at-wat** [pion/ice#216]
```
=== RUN   TestSTUNConcurrency
--- PASS: TestSTUNConcurrency (5.20s)
=== RUN   TestTURNConcurrency
=== RUN   TestTURNConcurrency/UDP_Relay
=== RUN   TestTURNConcurrency/TCP_Relay
turn ERROR: 2020/06/30 01:38:28 error when handling datagram: failed to handle Refresh-request from 127.0.0.1:32878: write udp 127.0.0.1:57202->127.0.0.1:32878: use of closed network connection
=== RUN   TestTURNConcurrency/TLS_Relay
=== RUN   TestTURNConcurrency/DTLS_Relay
turn ERROR: 2020/06/30 01:38:28 error when handling datagram: failed to handle Refresh-request from 127.0.0.1:45410: dtls fatal: use of closed network connection
--- PASS: TestTURNConcurrency (8.03s)
    --- PASS: TestTURNConcurrency/UDP_Relay (0.00s)
    --- PASS: TestTURNConcurrency/TCP_Relay (0.00s)
    --- PASS: TestTURNConcurrency/TLS_Relay (0.01s)
    --- PASS: TestTURNConcurrency/DTLS_Relay (0.01s)
=== RUN   TestSTUNTURNConcurrency
    TestSTUNTURNConcurrency: util.go:38: Unexpected routines on test end: 
        goroutine 725 [select]:
        github.com/pion/turn/v2/internal/client.(*PeriodicTimer).Start.func1(0xa881140, 0xa846a80)
        	/go/pkg/mod/github.com/pion/turn/v2@v2.0.3/internal/client/periodic_timer.go:47 +0xa0
        created by github.com/pion/turn/v2/internal/client.(*PeriodicTimer).Start
        	/go/pkg/mod/github.com/pion/turn/v2@v2.0.3/internal/client/periodic_timer.go:41 +0xab
        
        goroutine 724 [select]:
        github.com/pion/turn/v2/internal/client.(*PeriodicTimer).Start.func1(0xa881110, 0xa846a40)
        	/go/pkg/mod/github.com/pion/turn/v2@v2.0.3/internal/client/periodic_timer.go:47 +0xa0
        created by github.com/pion/turn/v2/internal/client.(*PeriodicTimer).Start
        	/go/pkg/mod/github.com/pion/turn/v2@v2.0.3/internal/client/periodic_timer.go:41 +0xab
--- FAIL: TestSTUNTURNConcurrency (10.40s)
```

**Comment by Sean-Der** [comment]
Looks like that is in the `pion/turn` Client. I will look into that right after `ICE Restarts` land! I have seen races reported before, maybe with some `go test -count 100` I can get to the bottom of it :)

**Comment by Sean-Der** [comment]
@at-wat I think I figured this out!

We are using a WaitGroup that can't respond to closing the `Agent`, after https://github.com/pion/ice/pull/224 lands I think I can get this fixed :)

**Comment by at-wat** [comment]
It happens very often after #225

**Comment by at-wat** [comment]
@Sean-Der I found that turn connection was not closed when the agent is closed during gathering.
