### ISSUE TITLE
Crash in sendStun

### ISSUE THREAD

**Issue by nerd2** [pion/ice#258]
### Your environment.
  - Version: v2.0.0-rc.4
  - Browser: Chrome  84.0.4147.105

### What did you do?
Closed and opened connections

### What did you expect?
Functional webrtc stream

### What happened?
Crash

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x55874340ac]

goroutine 5333 [running]:
repo.jazznetworks.com/vaion/vaion/vendor/github.com/pion/ice/v2.(*candidateBase).writeTo(0x40026f4960, 0x4000d0f700, 0x64, 0x80, 0x5587edcd00, 0x4003236fc0, 0x0, 0x0, 0x0)
	vendor/github.com/pion/ice/v2/candidate_base.go:185 +0x3c
repo.jazznetworks.com/vaion/vaion/vendor/github.com/pion/ice/v2.(*Agent).sendSTUN(0x40000d1b80, 0x400258f1d0, 0x5587edcc40, 0x40026f4960, 0x5587edcd00, 0x4003236fc0)
	vendor/github.com/pion/ice/v2/candidatepair.go:90 +0x5c
repo.jazznetworks.com/vaion/vaion/vendor/github.com/pion/ice/v2.(*Agent).sendBindingRequest(0x40000d1b80, 0x400258f1d0, 0x5587edcc40, 0x40026f4960, 0x5587edcd00, 0x4003236fc0)
	vendor/github.com/pion/ice/v2/agent.go:930 +0x274
repo.jazznetworks.com/vaion/vaion/vendor/github.com/pion/ice/v2.(*controllingSelector).PingCandidate(0x4003294980, 0x5587edcc40, 0x40026f4960, 0x5587edcd00, 0x4003236fc0)
	vendor/github.com/pion/ice/v2/selection.go:161 +0x2c4
repo.jazznetworks.com/vaion/vaion/vendor/github.com/pion/ice/v2.(*Agent).checkKeepalive(0x40000d1b80)
	vendor/github.com/pion/ice/v2/agent.go:692 +0xb4
repo.jazznetworks.com/vaion/vaion/vendor/github.com/pion/ice/v2.(*controllingSelector).ContactCandidates(0x4003294980)
	vendor/github.com/pion/ice/v2/selection.go:52 +0x2e4
repo.jazznetworks.com/vaion/vaion/vendor/github.com/pion/ice/v2.(*Agent).connectivityChecks.func1.1(0x5587ec20a0, 0x4002b29e00, 0x40000d1b80)
	vendor/github.com/pion/ice/v2/agent.go:494 +0xb8
repo.jazznetworks.com/vaion/vaion/vendor/github.com/pion/ice/v2.(*Agent).taskLoop(0x40000d1b80)
	vendor/github.com/pion/ice/v2/agent.go:218 +0x98
created by repo.jazznetworks.com/vaion/vaion/vendor/github.com/pion/ice/v2.NewAgent
	vendor/github.com/pion/ice/v2/agent.go:339 +0x664
```

**Comment by Sean-Der** [comment]
I think this was fixed by https://github.com/pion/ice/issues/247 

Not 100% sure though!

**Comment by Sean-Der** [comment]
Are you able to easily reproduce?

**Comment by nerd2** [comment]
No, can't reproduce, but looks plausible. Thanks Sean, i'll close.
