### ISSUE TITLE
TestMulticastDNSOnlyConnection frequently timeout in travis

### ISSUE THREAD

**Issue by hugoArregui** [pion/ice#75]
```
=== RUN   TestMulticastDNSOnlyConnection
ice ERROR: 2019/06/27 12:08:45 error processing checkCandidatesTimeout handler the agent is closed
goroutine profile: total 43
13 @ 0x4584ff 0x453a4a 0x453036 0x4b3f95 0x4b6745 0x4b6721 0x5f8df0 0x643091 0x64acc3 0x64aca4 0x6520f6 0x486771
#	0x453035	internal/poll.runtime_pollWait+0x55			/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/netpoll.go:182
#	0x4b3f94	internal/poll.(*pollDesc).wait+0xe4			/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/internal/poll/fd_poll_runtime.go:87
#	0x4b6744	internal/poll.(*pollDesc).waitRead+0x144		/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/internal/poll/fd_poll_runtime.go:92
#	0x4b6720	internal/poll.(*FD).RawRead+0x120			/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/internal/poll/fd_unix.go:534
#	0x5f8def	net.(*rawConn).Read+0x6f				/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/rawconn.go:43
#	0x643090	golang.org/x/net/internal/socket.(*Conn).recvMsg+0x3d0	/home/travis/gopath/pkg/mod/golang.org/x/net@v0.0.0-20190619014844-b5b0513f8c1b/internal/socket/rawconn_msg.go:31
#	0x64acc2	golang.org/x/net/internal/socket.(*Conn).RecvMsg+0x212	/home/travis/gopath/pkg/mod/golang.org/x/net@v0.0.0-20190619014844-b5b0513f8c1b/internal/socket/socket.go:255
#	0x64aca3	golang.org/x/net/ipv4.(*payloadHandler).ReadFrom+0x1f3	/home/travis/gopath/pkg/mod/golang.org/x/net@v0.0.0-20190619014844-b5b0513f8c1b/ipv4/payload_cmsg.go:31
#	0x6520f5	github.com/pion/mdns.(*Conn).start+0x155		/home/travis/gopath/pkg/mod/github.com/pion/mdns@v0.0.2/conn.go:249
8 @ 0x4584ff 0x453a4a 0x453036 0x4b3f95 0x4b5314 0x4b52ea 0x5ddc3a 0x6026ee 0x600546 0x86271a 0x486771
#	0x453035	internal/poll.runtime_pollWait+0x55			/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/netpoll.go:182
#	0x4b3f94	internal/poll.(*pollDesc).wait+0xe4			/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/internal/poll/fd_poll_runtime.go:87
#	0x4b5313	internal/poll.(*pollDesc).waitRead+0x213		/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/internal/poll/fd_poll_runtime.go:92
#	0x4b52e9	internal/poll.(*FD).ReadFrom+0x1e9			/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/internal/poll/fd_unix.go:219
#	0x5ddc39	net.(*netFD).readFrom+0x79				/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/fd_unix.go:208
#	0x6026ed	net.(*UDPConn).readFrom+0x8d				/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/udpsock_posix.go:47
#	0x600545	net.(*UDPConn).ReadFrom+0x95				/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/net/udpsock.go:121
#	0x862719	github.com/pion/ice.(*candidateBase).recvLoop+0x209	/home/travis/gopath/src/github.com/pion/ice/candidate_base.go:93
8 @ 0x4584ff 0x468e4b 0x85acc7 0x486771
#	0x85acc6	github.com/pion/ice.(*Agent).taskLoop+0x246	/home/travis/gopath/src/github.com/pion/ice/agent.go:557
6 @ 0x4584ff 0x468e4b 0x85af02 0x486771
#	0x85af01	github.com/pion/ice.(*Agent).taskLoop+0x481	/home/travis/gopath/src/github.com/pion/ice/agent.go:570
2 @ 0x4584ff 0x468e4b 0x6507a1 0x85b8f0 0x486771
#	0x6507a0	github.com/pion/mdns.(*Conn).Query+0x3d0				/home/travis/gopath/pkg/mod/github.com/pion/mdns@v0.0.2/conn.go:131
#	0x85b8ef	github.com/pion/ice.(*Agent).resolveAndAddMulticastCandidate+0x13f	/home/travis/gopath/src/github.com/pion/ice/agent.go:639
1 @ 0x4584ff 0x42e969 0x42e93f 0x42e6db 0x544833 0x54a799 0x544124 0x546784 0x544fdc 0x8a1d55 0x4580ec 0x486771
#	0x544832	testing.(*T).Run+0x692		/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:917
#	0x54a798	testing.runTests.func1+0xa8	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:1157
#	0x544123	testing.tRunner+0x163		/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:865
#	0x546783	testing.runTests+0x523		/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:1155
#	0x544fdb	testing.(*M).Run+0x2eb		/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:1072
#	0x8a1d54	main.main+0x344			_testmain.go:206
#	0x4580eb	runtime.main+0x20b		/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/proc.go:200
1 @ 0x4584ff 0x468e4b 0x85a94a 0x85d314 0x88f7a5 0x85af44 0x486771
#	0x85a949	github.com/pion/ice.(*Agent).run+0x189				/home/travis/gopath/src/github.com/pion/ice/agent.go:546
#	0x85d313	github.com/pion/ice.(*Agent).Close+0x103			/home/travis/gopath/src/github.com/pion/ice/agent.go:738
#	0x88f7a4	github.com/pion/ice.TestHandlePeerReflexive.func1.1+0xab4	/home/travis/gopath/src/github.com/pion/ice/agent_test.go:279
#	0x85af43	github.com/pion/ice.(*Agent).taskLoop+0x4c3			/home/travis/gopath/src/github.com/pion/ice/agent.go:573
1 @ 0x4584ff 0x468e4b 0x85a94a 0x85d314 0x88ffa6 0x85af44 0x486771
#	0x85a949	github.com/pion/ice.(*Agent).run+0x189				/home/travis/gopath/src/github.com/pion/ice/agent.go:546
#	0x85d313	github.com/pion/ice.(*Agent).Close+0x103			/home/travis/gopath/src/github.com/pion/ice/agent.go:738
#	0x88ffa5	github.com/pion/ice.TestHandlePeerReflexive.func2.1+0x335	/home/travis/gopath/src/github.com/pion/ice/agent_test.go:310
#	0x85af43	github.com/pion/ice.(*Agent).taskLoop+0x4c3			/home/travis/gopath/src/github.com/pion/ice/agent.go:573
1 @ 0x4584ff 0x468e4b 0x873f12 0x873a3b 0x887638 0x884da6 0x544124 0x486771
#	0x873f11	github.com/pion/ice.(*Agent).connect+0x361			/home/travis/gopath/src/github.com/pion/ice/transport.go:44
#	0x873a3a	github.com/pion/ice.(*Agent).Dial+0xaa				/home/travis/gopath/src/github.com/pion/ice/transport.go:15
#	0x887637	github.com/pion/ice.connect+0x4b7				/home/travis/gopath/src/github.com/pion/ice/transport_test.go:187
#	0x884da5	github.com/pion/ice.TestMulticastDNSOnlyConnection+0x435	/home/travis/gopath/src/github.com/pion/ice/mdns_test.go:44
#	0x544123	testing.tRunner+0x163						/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/testing/testing.go:865
1 @ 0x4584ff 0x468e4b 0x873f12 0x873b4b 0x89562a 0x486771
#	0x873f11	github.com/pion/ice.(*Agent).connect+0x361	/home/travis/gopath/src/github.com/pion/ice/transport.go:44
#	0x873b4a	github.com/pion/ice.(*Agent).Accept+0xaa	/home/travis/gopath/src/github.com/pion/ice/transport.go:21
#	0x895629	github.com/pion/ice.connect.func1+0x99		/home/travis/gopath/src/github.com/pion/ice/transport_test.go:182
1 @ 0x5b1a2e 0x5b17fa 0x5ad6ac 0x6a3fc7 0x486771
#	0x5b1a2d	runtime/pprof.writeRuntimeProfile+0x9d			/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/pprof/pprof.go:708
#	0x5b17f9	runtime/pprof.writeGoroutine+0xc9			/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/pprof/pprof.go:670
#	0x5ad6ab	runtime/pprof.(*Profile).WriteTo+0x4fb			/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/runtime/pprof/pprof.go:329
#	0x6a3fc6	github.com/pion/transport/test.TimeOut.func1+0x96	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.7.0/test/util.go:18
panic: timeout
goroutine 202 [running]:
github.com/pion/transport/test.TimeOut.func1()
	/home/travis/gopath/pkg/mod/github.com/pion/transport@v0.7.0/test/util.go:21 +0x164
created by time.goFunc
	/home/travis/.gimme/versions/go1.12.6.linux.amd64/src/time/sleep.go:169 +0x52
```

I tried increasing the timeout to 1 minute but it didn't help

**Comment by Sean-Der** [comment]
I think the only way to remove the flakiness of this test is using `vnet` :/

I haven't spent much time debugging, but I guess it is common for VPSes to not have multicast enabled. So we might be getting a server every once in a while without it. There could also be a bug! That wouldn't surprise me either.

**Comment by hugoArregui** [comment]
maybe we can move the test to its own file and add a build tag. And then we would only enable the tag if multicast is enabled for the interface?

**Comment by Sean-Der** [comment]
@hugoArregui oh that is a fantastic idea!

We can just have a quick pre-amble that tests if multicast works, if that fails we just skip the test!

I will take care of writing that up, really cool idea.
